### PR TITLE
Update backup and config generation systems

### LINKED ISSUE #63: Update standard scaffolding to use entrypoint config generation
After merging #60, we need to update scaffolding to make that one the default and deprecate old system.

### PR DESCRIPTION
**Pull request by Yajo**
- Use tecnativa/duplicity:postgres-s3 backup image by default.
- Use new entrypoint configuration generation system from #60.
- Fix #63.

### CODE REVIEW

**Comment by lasley** [comment]
Any reason to not just use Camptocamp's solution, [Conplicity](https://github.com/camptocamp/conplicity)? We've been using it for a few months, and I find it quite awesome.

**Comment by Yajo** [comment]
What does it offer above plain duplicity?

**Comment by lasley** [comment]
> What does it offer above plain duplicity?

Just automation scripts wrapped around Duplicity. The big one is detection of the data types on the volume, with support for DB dumps from most of the standard database types. This in comparison to running the DB dump (mysql_dump, pg_dump, etc) and subsequently backing up the dump.

**Comment by Yajo** [comment]
Well... maybe if our version wasn't already done... but it is, and it's much simpler IMHO.

In any case, it's only part of the scaffolding. You can use your own backup tool or scaffolding (see https://github.com/Tecnativa/docker-odoo-base#can-i-have-my-own-scaffolding).

**Pull request merged**
